### ISSUE TITLE
Consider using .g.(ts/js) file extension

### ISSUE THREAD

**Issue by rmjohnson** [FacilityApi/FacilityJavaScript#24]
I'm moving from using our generated client as a published NPM packge to using it directly in the consumer (this is a BFF, so only has the one consumer). Because the generated client is now living alongside other non-generated clients we have it stuck out to me that these generated client file names don't have the `.g.(ts/js)` file extension like we use in [`FacilityCSharp`](https://github.com/FacilityApi/FacilityCSharp/blob/1bdedab17e5d29964a312caa98c65289da4b75aa/src/Facility.CodeGen.CSharp/CSharpUtility.cs#L57). 

Thoughts? I can open a PR for this change if there is consensus.

**Comment by rmjohnson** [comment]
CC: @ejball

**Comment by rmjohnson** [comment]
FWIW I ended up putting these in a separate folder so I think it is clear *enough* that they are different so not blocking me or anything, just a thought I had.

**Comment by ejball** [comment]
I can't find any precedent for using `.g.js` or `.g.ts`, except in [Logos/rich-text-js](https://git.faithlife.dev/Logos/rich-text-js). It does make `import` statements on those files look a little odd, especially if you drop the `.js`, e.g. `import { RichTextInline } from './inline.g';`

**Comment by rmjohnson** [comment]
That's a good point on imports. 👍
