### ISSUE TITLE
Deploy facility-core via automated build

### ISSUE THREAD

**Issue by ejball** [FacilityApi/FacilityJavaScript#6]
The NuGet packages can now be deployed by creating a release tag, e.g. `v2.3.4`. Should we deploy the npm package the same way? Should we keep their version numbers in sync or continue to use separate version numbers?

**Comment by ejball** [comment]
Any thoughts, @ddunkin?

**Comment by ddunkin** [comment]
If one packages changes, but not the other, and we want to keep the version numbers in sync, would we release an unchanged package or skip version numbers? Both are unappealing.

Some monorepo projects use tags with a prefix indicating the component. For this scenario, that could be something like `nuget-v2.3.4` and `npm-v.1.2.3`.

**Comment by ejball** [comment]
Sounds reasonable. If you support `npm-v1.2.3`, I'll change `v1.2.3` support to `nuget-v1.2.3`. :-)

Hopefully we can support prerelease (e.g. `npm-v1.2.3-beta`) as well...

**Comment by ejball** [comment]
@ddunkin, `nuget-` support for tags is in for v2.
